AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  addfriends:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.fn
      Runtime: nodejs10.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 43
      Role: 'arn:aws:iam::151459647553:role/service-role/addfriends-role-7j1953en'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /friends
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
